### PR TITLE
issue #20 adding connector jars

### PR DESCRIPTION
**Pull request by KurtStam**
@mattrpav The package name of the connector is `com.redhat.ipaas`. Also the sub package structure is slightly different then what you have, for salesforce at least. So I think I will need an update atlas mapping.json from you to reflect this.

### CODE REVIEW

**Comment by chirino** [comment]
LGTM

**Comment by KurtStam** [comment]
retest please

**Comment by iocanel** [comment]
retest this please

**Comment by iocanel** [comment]
retest this

**Comment by iocanel** [comment]
retest this

**Comment by iocanel** [comment]
retest this

**Comment by KurtStam** [comment]
merge please

**Comment by KurtStam** [comment]
[merge]

**Pull request merged**
