### PR TITLE
Setup a pipeline config so we can build and roll this project into staging.

### PR DESCRIPTION
**Pull request by chirino**

### CODE REVIEW

**Comment by chirino** [comment]
retest this please

**Comment by zregvart** [comment]
retest this please

**Comment by chirino** [comment]
retest this please

**Comment by zregvart** [comment]
retest this please

**Comment by iocanel** [comment]
LGTM

**Comment by zregvart** [comment]
retest this please

**Comment by chirino** [comment]
retest this please

**Pull request merged**
